config/routes.rb
Rails.application.routes.draw do
  get 'map/view'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#about'
  get "/apply" => "messages#apply", as: "apply"
  post "/apply" => "messages#postapply"

  resources :fundraisers

  resource :session, only: %i(new create destroy)

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  get "/about" => "home#about", as: 'about'
  get "/map" => "map#view", as: "map"


  get '/contact' => "messages#new", as: "contact"
  post '/contact' => "messages#create", as: "messages"

end

app/models/application.rb
class Application < ApplicationRecord
  include ActiveModel::Model
  attr_accessor :firstname,
                :lastname,
                :hebname,
                :DOB,
                :place_of_birth,
                :age,
                :grade,
                :school,
                :address,
                :city,
                :prov,
                :ZIP,
                :home_phone,
                :camper_cell,
                :camper_email,
                :emg_contact,
                :emg_contact_phone,
                :health_card,
                :med_info,
                :other_info,
                :ref1,
                :ref1_school_phone,
                :ref1_phone,
                :ref2,
                :ref2_school_phone,
                :ref2_phone,
                :father,
                :d_marital_status,
                :d_occupation,
                :d_h_phone,
                :d_cell,
                :d_b_phone,
                :d_email,
                :mother,
                :m_marital_status,
                :m_occupation,
                :m_h_phone,
                :m_cell,
                :m_b_phone,
                :m_email,
                :synagogue,
                :rabbi, :session

  validates :firstname, :lastname, presence: true
  # canadian_postal_code = /\A[ABCEGHJKLMNPRSTVXY]{1}\\d{1}[A-Z]{1}[ -]?\\d{1}[A-Z]{1}\\d{1}\z/
  # validates :ZIP, format: { with: canadian_postal_code }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fundraiser.rb
class Fundraiser < ApplicationRecord

    has_secure_password

    validates_length_of :password, :in => 8..20, :on => :create
  
    # devise :omniauthable, :omniauth_providers => [:google_oauth2] 

    def full_name
        "#{self.fname} #{self.lname}"
     end
    
end

app/models/message.rb
class Message
    include ActiveModel::Model
    attr_accessor :name, :email, :phone_number, :body
    validates :name, :email, :body, presence: true
end

app/models/place.rb
class Place < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

        protect_from_forgery with: :exception 
        helper_method :current_user
        
        def authenticate_user! 
           redirect_to ‘/login’ unless current_user 
        end 

        def current_user
                @current_user ||= Fundraiser.find_by(id: session[:user_id]) if session[:user_id] 
        end 
        

end

app/controllers/fundraisers_controller.rb
class FundraisersController < ApplicationController

  # before_action :require_login, except: [:index, :new, :create, :show]
  before_action :require_ownership, only: [:edit, :update, :destroy]

    def index
        @fundraisers = Fundraiser.all
    end

    def show
      @fundraiser = Fundraiser.find(params[:id])
    end


    def new
        @fundraiser = Fundraiser.new 
    end

    def create
        @fundraiser = Fundraiser.new(fundraiser_params)

        if @fundraiser.save
          session[:user_id] = @fundraiser.id #to login fundie
          flash[:notice] = "You signed up successfully"
          redirect_to fundraisers_url
        else
          flash[:notice] = "Form is invalid"
          render "new"
        end
          return @fundraiser.errors.full_messages
    end
    
    def edit 
      @fundraiser = Fundraiser.find(params[:id])
    end

    def update
      @fundraiser = Fundraiser.find(params[:id])

      if @fundraiser.update_attributes(fundraiser_params)
        redirect_to fundraiser_url(@fundraiser)
 
      else
          render :edit
      end
    end

    def destroy
      Fundraiser.find(params[:id]).destroy
      redirect_to root_path
    end


    private
    def fundraiser_params
      params.require(:fundraiser).permit(:fname, :lname, :email, :username, :password)
    end

    def require_login
      unless session[:user_id]
        flash[:error] = "You must be logged in to access this section"
        redirect_to new_session_path
      end
    end

    def require_ownership
      @fundraiser = Fundraiser.find(params[:id])

      unless @fundraiser == current_user
        flash[:error] = "You are not the correct user"
        redirect_to root_path
      end
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def about
    end

end

app/controllers/map_controller.rb
class MapController < ApplicationController

  def view
    @maps_api_key = Figaro.env.google_maps_api_key
    @bjhs = Place.find_by(name:"BJHS")
    @overnight = Place.find_by(name:"Overnight")
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    def new
        @message = Message.new
    end

    def create
        @message = Message.new(message_params)

        respond_to do |format|
            if @message.valid?
              MailerMailer.with(message: params[:message]).contact.deliver
              format.html {redirect_to(root_path) }
              MailerMailer.with(message: params[:message]).auto_reply.deliver    
              format.html 
            else
              format.html { render action: 'new'  }
              flash.now.alert = "Please fill in all the required boxes"
            end
          end
    end

    def apply
      @apply = Application.new
      render "apply.html.erb"
    end

    def postapply
      # @apply = Application.new(application_params)

      respond_to do |format|
          # if @apply.valid?
            MailerMailer.with(application: params[:application]).application.deliver
            format.json {redirect_to(root_path) }
          #   MailerMailer.with(message: params[:application]).auto_reply.deliver    
          #   format.html 
          # else
            # flash.now.alert = "Please fill in all the required boxes"
            # format.html { render action: 'new'  }
          # end
        end

    end

    private 
    def message_params
        params.require(:message).permit(:name, :email, :phone_number, :body)
    end

    def application_params
      params[:application]
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    # 
    def create
        u = Fundraiser.find_by(username: params[:session][:username])

    if u && u.authenticate(params[:session][:password])
      # Put on the wristband

      session[:user_id] = u.id
      redirect_to root_url, notice: "Logged in"
    else
        # flash[:warning] = 'Email or password invalid!'
        flash.now.alert = "Email or password is invalid."
        render :new
    end
  end

  def destroy
    # Cut the wristband
    session[:user_id] = nil

    flash[:success] = 'Successfully logged out'
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fundraisers_helper.rb
module FundraisersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/fundraisers/_form.html.erb
 <%= form_for(@fundraiser) do |f| %>


    <p> First Name:</br> <%= f.text_field :fname %> </p>
    <p> Last Name:</br> <%= f.text_field :lname %> </p>
      <% if @fundraiser.new_record? %>
        <p> Username:</br> <%= f.text_field :username %> </p>   
      <% end %>

    <p> Country:</br> <%= f.country_select :country, priority_countries: ["CA", "US", "IL"] %> </p>

    <p> Email:</br> <%= f.email_field :email %> </p>

    <p> Fundraising Goal:</br> $<%= f.number_field :goal, value: "3600", min: '10', step: '10' %>  </p>

    <% unless @fundraiser.new_record? %>
        <p> Old Password:</br> <%= f.password_field :old_password %> </p>   
      <% end %>

    <br><p> Password:</br> <%= f.password_field :password  %></p>

    <p> Password confirm:</br> <%= f.password_field :password_confirmation %></p>



    <%= f.submit "Submit!" %>
  <% end %>

app/views/fundraisers/edit.html.erb
<h1>Edit Your Info</h1>


    <%= render partial: 'form' %>

app/views/fundraisers/index.html.erb
    <h1>Find a Raiser!</h1>

<% if @fundraisers.any? %>
    <% @fundraisers.each do |t| %>

        <%= link_to t.full_name, fundraiser_url(t) %><br/>
        
    <% end %>
<% end %>

app/views/fundraisers/new.html.erb
<div class = "mailer" >
<h1>Sign Up!</h1>

<%= render partial: "form" %>
</div>
   

app/views/fundraisers/show.html.erb
<h1> <%= @fundraiser.full_name %> </h1>

<p>
<%= @fundraiser.goal %>
<%= @fundraiser.username %>

</p>




<%if current_user == @fundraiser %>
    <%= link_to "Edit", edit_fundraiser_path %>
    <%= link_to "Delete this User", fundraiser_path(@fundraiser), method: :delete, 
    data: {confirm: "are you sure you want to delete?"} %>
<% end %>

app/views/home/_slideshow.html.erb
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag("group_water.jpg", style:"width: 100%")%>
    </div>
    
    <div class="item">
        <%= image_tag("height.jpg", style:"width: 100%")%>
    </div>

    <div class="item">
        <%= image_tag("girls.jpg", style: "width: 100%;")%>
    </div>

    <div class="item">
        <%= image_tag("rainbow.jpg", style:"width: 100%")%>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/home/about.html.erb
<div class="about">
    <h1>
        About Us
    </h1>

    <b>Ashreinu</b> is an organization that serves hundreds of children, teens, and their families each year. In the
    most amazing and unique display of Ahavas Yisroel, we connect every type of Jew. Ashreinu instills Jewish pride,
    love for Judaism, and Jewish continuity in all who are involved. Both our staff and families grow in their love and
    commitment to Judaism.

    <h2>What's New:</h2>
    <%# image stored in app/assets/images %>
    <%# styling to fit image in div found in home.scss %>
    <%= image_tag("ashreinu-purim-carnival-flyer-2020.jpg", class: "image_tag") %>
    <br/>
    <%= image_tag("PHOTO-2020-02-27-00-48-14.jpg", class: "image_tag") %>

    <h2>Our Programs:</h2>

    <div class="card-container">
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front" id="night-card-front">
                    <h3>Overnight Camp</h3>
                </div>
                <div class="flip-card-back" id="night-card-back">
                    <div>
                        <h3>Overnight Camp</h3>
                        <p>The highlight of our year! A chance for our 100 girls to live Judaism. 100 girls of all
                            different
                            levels of Judaism live a joyfully Jewish summer.</p>
                        <p>As our slogan goes: Ashreinu - Live it, experience it!</p>
                        <p>Ashreinu prides itself for being the only Jewish outreach overnight camp in Canada.</p>
                            <p><%= link_to 'Download the 2020 overnight camp application','/Ashreinu_2020_night_application.pdf', download: '', class: "app_link" %> </p>
                   </div>
                </div>
            </div>
        </div>

        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front" id="day-card-front">
                    <h3>Day Camp</h3>
                </div>
                <div class="flip-card-back">
                    <div>
                        <h3>Day Camp</h3>
                        <p> In the heart of Toronto, 150 campers and staff enjoy a full summer of living joyful Judaism.
                            Our campers spend the day engaged in fun activities where they can also learn about their
                            Judaism.
                            Kosher meals and snacks are provided. The bond they forge with staff members will last
                            throughout the year! </p>
                        <p><%= link_to 'Download the 2020 day camp application','/Ashreinu_2020_day_application.pdf', download: '', class: "app_link" %></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front" id="shab-card-front">
                    <h3>Shabbatonim</h3>
                </div>
                <div class="flip-card-back">
                    <div>
                        <h3>Shabbatons</h3>
                        <p>Numerous times throughout the year, the girls join their favourite staff members for Shabbos.
                            Girls are hosted by local families and get a taste of what we hope will be one Shabbos of
                            many! We host separate Shabbatons are for all age groups, elementary students through teens. Our annual spring retreat
                            is an exclusive Shabbaton for 100 girls
                            held in a hotel location. We have also hosted smaller Shabbatons in communities, such as
                            Hamilton, to bring
                            the
                            Ashreinu spirit to girls who do not have the benefit of the Ashreinu experience. </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

app/views/layouts/_footer.html.erb
<!-- Site footer -->
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>Contact</h6>
            <ul class="footer-links">
              <li>CampAshreinu123@gmail.com</li>

            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <%# <h6>Categories</h6>
            <ul class="footer-links">
              <li><a href="http://scanfcode.com/category/c-language/">C</a></li>
              <li><a href="http://scanfcode.com/category/front-end-development/">UI Design</a></li>
              <li><a href="http://scanfcode.com/category/back-end-development/">PHP</a></li>
              <li><a href="http://scanfcode.com/category/java-programming-language/">Java</a></li>
              <li><a href="http://scanfcode.com/category/android/">Android</a></li>
              <li><a href="http://scanfcode.com/category/templates/">Templates</a></li>
            </ul> %>
          </div>

          <div class="col-xs-6 col-md-3">
            <%# <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><a href="http://scanfcode.com/about/">About Us</a></li>
              <li><a href="http://scanfcode.com/contact/">Contact Us</a></li>
              <li><a href="http://scanfcode.com/contribute-at-scanfcode/">Contribute</a></li>
              <li><a href="http://scanfcode.com/privacy-policy/">Privacy Policy</a></li>
              <li><a href="http://scanfcode.com/sitemap/">Sitemap</a></li>
            </ul> %>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Designed by Yehudis Dick
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>   
            </ul>
          </div>
        </div>
      </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Ashreinu</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="google-site-verification" content="7h7kUbUt0nOegrVDUtO5mllqbOwWBHYPmfEG3MP8Rv4" />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= favicon_link_tag asset_path('ashreinu_logo.jpg') %>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

</head>

<body>

  <div class="background">
 
    <div class="navbar-wrapper">
      <nav class="navbar navbar-transparent" role="navigation">
        <div class="container-fluid">

          <div class="navbar-header">
            <a class="navbar-brand" href="<%=root_path%>">
            <%= image_tag("ashreinu-logo-alone.png", size: "100x90")%>
            </a>
          </div>

          <ul class="nav navbar-nav navbar-center">
            <li>
              <a href=<%= about_path %>>About</a>
            </li>
            <li>
              <a href=<%= map_path %>>Map</a>
            </li>
            <li>
              <a href="<%= contact_path %>">Contact Us</a>
            </li>
            <li>
              <a href="<%= apply_path %>">Apply!</a>
            </li>
          </ul>
          <div class="nav navbar-nav navbar-right">
              <%= link_to image_tag("social/001-instagram.png", :size => "20px"), "https://www.instagram.com/ashreinutoronto/?hl=en", target: "_blank"%>
          </div>
        </div>
      </nav>
    </div>

    <%# display static flash message %>
    <div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: 'alert alert-info' %>
      <% end %>
    </div>

      <div class="content">
      <%= yield %>
      </div>


  </div>

</body>
<!-- Site footer -->
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6><%=link_to 'Contact', contact_path %></h6>
            <ul class="footer-links">
              <li>CampAshreinu123@gmail.com</li>
              <li>416.787.1489</li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <%# <h6>Categories</h6>
            <ul class="footer-links">
              <li><a href="http://scanfcode.com/category/c-language/">C</a></li>
              <li><a href="http://scanfcode.com/category/front-end-development/">UI Design</a></li>
              <li><a href="http://scanfcode.com/category/back-end-development/">PHP</a></li>
              <li><a href="http://scanfcode.com/category/java-programming-language/">Java</a></li>
              <li><a href="http://scanfcode.com/category/android/">Android</a></li>
              <li><a href="http://scanfcode.com/category/templates/">Templates</a></li>
            </ul> %>
          </div>

          <div class="col-xs-6 col-md-3">
            <%# <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><a href="http://scanfcode.com/about/">About Us</a></li>
              <li><a href="http://scanfcode.com/contact/">Contact Us</a></li>
              <li><a href="http://scanfcode.com/contribute-at-scanfcode/">Contribute</a></li>
              <li><a href="http://scanfcode.com/privacy-policy/">Privacy Policy</a></li>
              <li><a href="http://scanfcode.com/sitemap/">Sitemap</a></li>
            </ul> %>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Designed by Yehudis Dick
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <%# <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li> %>
              <%# <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li> %>
              <li><a class="dribbble" href="https://www.instagram.com/ashreinutoronto/?hl=en" target="_blank"><i class="fa fa-instagram"></i></a></li>
              <%# <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>    %>
            </ul>
          </div>
        </div>
      </div>
</footer>

</html>

app/views/messages/_application_form.html.erb
<%= form_for(@apply, url: apply_path, :html => {:class => "form-inline"}) do |f| %>

<h3>General Information</h3>
<div class="form-group">
  <label for="name">Child's Last Name</label>
  <%= f.text_field :lastname,  class:"form-control", :required => true%> </p>
</div>
<div class="form-group">
  <label for="name">First Name</label>
  <%= f.text_field :firstname, class:"form-control", :required => true%> </p>
</div>

<div class="form-group">
  <label for="hebname">Hebrew Name</label>
  <%= f.text_field :hebname, class:"form-control"%> </p>
</div>
<br />
<div class="form-group">
  <label for="DOB">Date of Birth</label>
  <%= f.date_select :DOB, class:"form-control", start_year: Date.today.year - 25 , end_year: Date.today.year - 2 %> </p>
</div>

<div class="form-group">
  <label for="place_of_birth">Place of Birth</label>
  <%= f.text_field :place_of_birth, class:"form-control" %> </p>
</div>

<div class="form-group">
  <label for="age">Age</label>
  <%= f.number_field :age, class:"form-control" %> </p>
</div>

<br />

<div class="form-group">
  <label for="school">School</label>
  <%= f.text_field :school, class:"form-control"  %> </p>
</div>

<div class="form-group">
  <label for="grade">Grade Completed</label>
  <%= f.text_field :grade, class:"form-control"  %> </p>
</div>

<br>

<div class="form-group">
  <%= f.label :address%>
  <%= f.text_field :address, class:"form-control"  %> </p>
</div>
<div class="form-group">
  <%= f.label :city%>
  <%= f.text_field :city, class:"form-control"  %> </p>
</div>
<div class="form-group">
  <%= f.label :prov%>
  <%= f.text_field :prov, class:"form-control"  %> </p>
</div>
<div class="form-group">
  <%= f.label :ZIP %>
  <%= f.text_field :ZIP, class:"form-control"  %> </p>
</div>

<br>

<div class="form-group">
  <label for="home_phone">Home Phone</label>
  <%= f.text_field :home_phone, class:"form-control"  %> </p>
</div>
<div class="form-group">
  <label for="camper_cell">Camper Cell</label>
  <%= f.text_field :camper_cell, class:"form-control"  %> </p>
</div>

<div class="form-group">
  <label for="camper_email">Camper Email</label>
  <%= f.text_field :camper_email, class:"form-control"  %> </p>
</div>
<br>

<div class="form-group">
  <label for="emg_contact">Emergency Contact</label>
  <%= f.text_field :emg_contact, class:"form-control"  %> </p>
</div>

<div class="form-group">
  <label for="emg_contact_phone">Emergency Contact Phone</label>
  <%= f.text_field :emg_contact_phone, class:"form-control"  %> </p>
</div>

<h3>Medical Information</h3>

<div class="form-group">
  <label for="health_card">Health Card Number</label>
  <%= f.text_field :health_card, class:"form-control"  %> </p>
</div>

  <p>Is there any special information which is important to know?</p>
<div class="form-group">
  <label for="med_info">Medical:</label>
  <%= f.text_field :med_info, class:"form-control",  :cols => "10", :rows => "10" %> </p>
</div>

<div class="form-group">
  <label for="other_info">Other:</label>
  <%= f.text_field :other_info, class:"form-control"  %> </p>
</div>

<h3>References</h3>
<h5>(Principal, Teacher)</h5>
<div class = "grid-container">
<div id = "ref1">
<div class="form-group">
  <label for="ref1">Reference 1</label>
  <%= f.text_field :ref1, class:"form-control"  %> </p>
</div>
<div class="form-group">
  <label for="ref1_school_phone">School Phone</label>
  <%= f.text_field :ref1_school_phone, class:"form-control"  %> </p>
</div>
<div class="form-group">
  <label for="ref1_phone">Home Phone</label>
  <%= f.text_field :ref1_phone, class:"form-control"  %> </p>
</div>
</div>

<div id="ref2">
<div class="form-group">
  <label for="ref2">Reference 2</label>
  <%= f.text_field :ref2, class:"form-control"  %> </p>
</div>
<div class="form-group">
  <label for="ref2_school_phone">School Phone</label>
  <%= f.text_field :ref2_school_phone, class:"form-control"  %> </p>
</div>
<div class="form-group">
  <label for="ref2_phone">Home Phone</label>
  <%= f.text_field :ref2_phone, class:"form-control"  %> </p>
</div>
</div>
</div>

<h3>Family Information </h3><h5>(If single parent, please include applicable information and addresses) </h5>
<div class = "grid-container">
<div id = "father">
<div class="form-group">
  <%= f.label :father%>
  <%= f.text_field :father, class:"form-control"  %> </p>
</div>

<div class="form-group">
  <label for="d_martial_status">Marital Status</label>
  <%= f.text_field :d_marital_status, class:"form-control"  %> </p>
</div>

<div class="form-group">
  <label for="d_occupation">Occupation</label>
  <%= f.text_field :d_occupation, class:"form-control"  %> </p>
</div>
<div class="form-group">
  <label for="d_h_phone">Home Phone</label>
  <%= f.text_field :d_h_phone, class:"form-control"  %> </p>
</div>
<div class="form-group">
  <label for="d_cell">Cell Phone</label>
  <%= f.text_field :d_cell, class:"form-control"  %> </p>
</div>

<div class="form-group">
  <label for="d_b_phone">Business Phone</label>
  <%= f.text_field :d_b_phone, class:"form-control"  %> </p>
</div>
<div class="form-group">
  <label for="d_email">Email</label>
  <%= f.text_field :d_email, class:"form-control"  %> </p>
</div>
</div>
<div id="mother">
<div class="form-group">
  <%= f.label :mother%>
  <%= f.text_field :mother, class:"form-control"  %> </p>
</div>

<div class="form-group">
  <label for="m_martial_status">Marital Status</label>
  <%= f.text_field :m_marital_status, class:"form-control"  %> </p>
</div>

<div class="form-group">
  <label for="m_occupation">Occupation</label>
  <%= f.text_field :m_occupation, class:"form-control"  %> </p>
</div>
<div class="form-group">
  <label for="m_h_phone">Home Phone</label>
  <%= f.text_field :m_h_phone, class:"form-control"  %> </p>
</div>
<div class="form-group">
  <label for="m_cell">Cell Phone</label>
  <%= f.text_field :m_cell, class:"form-control"  %> </p>
</div>

<div class="form-group">
  <label for="m_b_phone">Business Phone</label>
  <%= f.text_field :m_b_phone, class:"form-control"  %> </p>
</div>
<div class="form-group">
  <label for="m_email">Email</label>
  <%= f.text_field :m_email, class:"form-control"  %> </p>
</div>
</div>
</div>

<h3>Jewish Affiliation</h3>
<div class="form-group">
  <label for="synagogue">Synagogue</label>
  <%= f.text_field :school, class:"form-control"  %> </p>
</div>

<div class="form-group">
  <label for="rabbi">Rabbi</label>
  <%= f.text_field :rabbi, class:"form-control"  %> </p>
</div>

<br>
<div class="form-group">
  <label for="session"><h3>Session Attending</h3></label>
  <%= f.text_field :session, class:"form-control"%> </p>
</div>

<br>

<%= f.submit "Submit", class: "btn btn-default btn-primary",data: { confirm: 'Are you ready to submit your application?'} %>

<% end %>